set -sg repeat-time 0
set -s escape-time 0 # faster command sequences
set -g status-interval 5
set -g mode-keys vi

set-option -g focus-events on
set-option -g allow-rename off

set-window-option -q -g utf8 on

set-option -ga terminal-overrides ",alacritty:Tc"
set -g default-terminal "alacritty"

# Increase scrollback buffer to 10000
set -g history-limit 10000

# Mouse mode
set -g mouse on

# Silence
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Status Bar - zenburned (https://github.com/marcos-venicius/zenburned)
set -g status-bg "#0E0E0E"
set -g status-fg "#EAEADC"

set -g status-position bottom
set -g status-justify left
set -g status-style 'bg=#0E0E0E fg=#EAEADC'
set -g status-left ''
set -g status-right '#[fg=#2B2B2B,bg=#0E0E0E]#[fg=#EAEADC,bg=#2B2B2B] %d/%m #[fg=#9FC59F,bg=#2B2B2B]#[fg=#0E0E0E,bg=#9FC59F] %H:%M:%S '
set -g status-right-length 50
set -g status-left-length 20

setw -g window-status-current-style 'fg=#0E0E0E bg=#9FC59F bold'
setw -g window-status-current-format ' #I#[fg=#2F4F2F]:#[fg=#0E0E0E]#W#[fg=#2F4F2F]#F #[fg=#9FC59F,bg=#0E0E0E]'

setw -g window-status-style 'fg=#858575 bg=#0E0E0E'
setw -g window-status-format ' #I#[fg=#858575]:#[fg=#858575]#W#[fg=#858575]#F '

setw -g window-status-activity-style 'fg=#F0E6B4 bg=#0E0E0E'
setw -g window-status-bell-style 'fg=#0E0E0E bg=#F0E6B4 bold'

# Panes
set -g pane-border-style 'fg=#2B2B2B'
set -g pane-active-border-style 'fg=#9FC59F'
set -g display-panes-colour '#7CA0A3'
set -g display-panes-active-colour '#9FC59F'

# Messages / command prompt
set -g message-style 'fg=#0E0E0E bg=#F0E6B4 bold'
set -g message-command-style 'fg=#FFFFFF bg=#383838'

# Copy mode / selection
set -g mode-style 'fg=#FFFFFF bg=#383838'
set -g clock-mode-colour '#9CDCDA'

# Bindings

unbind c
bind r source-file ~/.tmux.conf
bind-key a run-shell -b "/home/dev/tools/auth-to-commands/bypass.sh | xargs -I {} tmux display-message -d 2000 '{}' >/dev/null"

bind N new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind -r L select-window -l

bind -T copy-mode-vi y send-keys -X copy-pipe 'xclip -in -selection clipboard'
