return {
  "folke/snacks.nvim",
  priority = 1000,
  lazy = false,
  opts = {
    bigfile = { enabled = true },
    dashboard = { enabled = false },
    explorer = { enabled = false },
    image = { enabled = false },
    indent = { enabled = false },
    input = { enabled = true },
    notifier = { enabled = true, timeout = 3000, width = { min = 0.5, max = 0.6 } },
    picker = { enabled = false },
    quickfile = { enabled = true },
    scope = { enabled = true },
    scroll = { enabled = false },
    statuscolumn = { enabled = true },
    words = { enabled = false },
    styles = { notification = {} },
    gh = {},
  },
  keys = {
    { "<leader>ls", function() Snacks.picker.lsp_symbols() end, desc = "Document Symbols" },
    { "<leader>lS", function() Snacks.picker.lsp_workspace_symbols() end, desc = "Workspace Symbols" },
    { "<leader>x", function() Snacks.picker.explorer() end, desc = "File Explorer" },
    { "<leader>F", function() Snacks.picker.files() end, desc = "Files" },
    { "<leader>d", function() Snacks.picker.diagnostics() end, desc = "Diagnostics" },
    { "<leader>b", function() Snacks.picker.buffers() end, desc = "Buffers" },
    { "<leader>G", function() Snacks.picker.grep() end, desc = "Grep" },

    { "<leader>gd", function() Snacks.picker.git_diff() end, desc = "Git Diff" },
    { "<leader>gf", function() Snacks.picker.git_files() end, desc = "Git Files" },
    { "<leader>gl", function() Snacks.picker.git_log() end, desc = "Git Log" },
    { "<leader>gb", function() Snacks.picker.git_branches() end, desc = "Git Log" },
    { "<leader>/", function() Snacks.picker.git_grep() end, desc = "Git Grep" },

    { "<leader>nn", function() Snacks.notifier.show_history() end, desc = "Notification History" },
    { "<leader>nd", function() Snacks.notifier.hide() end, desc = "Dismiss All" },

    { "gd", function() Snacks.picker.lsp_definitions() end, desc = "Definition" },
    { "gD", function() Snacks.picker.lsp_declarations() end, desc = "Declaration" },
    { "gr", function() Snacks.picker.lsp_references() end, nowait = true, desc = "References" },
    { "gI", function() Snacks.picker.lsp_implementations() end, desc = "Implementation" },
    { "gy", function() Snacks.picker.lsp_type_definitions() end, desc = "Type Definition" },
  },
}

