#theme = "penumbra+"
#theme = "papercolor-dark"
#theme = "onedarker"
#theme = "onedark"
theme = "jetbrains_dark"
# theme = "everblush"

[editor]
bufferline = "always"
line-number = "relative"
cursorline = true
default-line-ending = "lf"
auto-format = false

[editor.cursor-shape]
insert = "bar"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
tab = "all"
space = "none"

[keys.normal."space"]
"o" = "file_picker_in_current_buffer_directory"
